package omari.hamza.storyview.model;

public enum StoryTextFont {
    APP_ROBOTO_BOLD,
    CAIRO_BOLD,
    POPPINS_BOLD,
    POPPINS_LIGHT,
    POPPINS_REGULAR,
    POPPINS_SEMI_BOLD,
    ROBOTO_MEDIUM,
    ROBOTO_REGULAR,
    SF_PRO_DISPLAY_MEDIUM,
    SOURCE_SAN_PRO_SEMIBOLD,
    SOURCE_SAN_PROBOLD
}
